---
name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install pipenv
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install Dependencies
        run: |
          pipenv --python ${{ matrix.python-version }} install --dev
          pipenv run pip list
        env:
          PIPENV_VENV_IN_PROJECT: true

      - name: Run Linting
        run: |
          pipenv run flake8 LittleLemonAPI/
          # continue-on-error: true

      - name: Run Migrations
        run: |
          pipenv run python manage.py makemigrations --check
          pipenv run python manage.py migrate
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: "sqlite:///:memory:"

      - name: Collect Static Files
        run: |
          mkdir -p static
          touch static/favicon.ico
          pipenv run python manage.py collectstatic --noinput
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: "sqlite:///:memory:"

      - name: Run Tests
        run: |
          pipenv run python manage.py test LittleLemonAPI
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: "sqlite:///:memory:"